/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Lighthouse.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Lighthouse.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 5.407, 0]} scale={0.292}>
        <mesh geometry={nodes.uploads_files_220346_Lindau_Lighthouse_1.geometry} material={materials.Default} />
        <mesh geometry={nodes.uploads_files_220346_Lindau_Lighthouse_2.geometry} material={materials.Brass} />
        <mesh geometry={nodes.uploads_files_220346_Lindau_Lighthouse_3.geometry} material={materials.Light} />
        <mesh geometry={nodes.uploads_files_220346_Lindau_Lighthouse_4.geometry} material={materials.Dark} />
      </group>
      <group position={[2.322, 2.921, -0.999]} rotation={[0, 0.47, 0]} scale={[6.488, 2.488, 3.567]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.StoneFloor} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.BrickWall} />
      </group>
      <mesh geometry={nodes.WaterLevel.geometry} material={materials.LevelIndicator} position={[2, 4, 3]} rotation={[0, 0.269, 0]} scale={[0.024, 0.236, 0.006]} />
      <group position={[0, 13.693, 0]} scale={1.051}>
        <mesh geometry={nodes.Circle001.geometry} material={materials.Brass} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lighthouse.glb')
