/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Balloon.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ pressure = 965, trigger }, props) {
  const { nodes, materials } = useGLTF('./models/Balloon.glb');
  // const pressureLevel = pressure - 960;
  const pressureLevel = 9;
  return (
    <group
      {...props}
      dispose={null}
      position={[0, -10.1, 0]}
      onPointerOver={(event) => (event.stopPropagation(), trigger('pressure'))}
      onPointerOut={(event) => trigger('')}
    >
      <mesh
        geometry={nodes.Sphere_Sphere002.geometry}
        material={materials.Default}
        position={[-6.879, 16.64 - pressureLevel / 5, 6.411]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.623}
      />
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials.Rope}
        position={[-6.879, 14.735 - pressureLevel / 5, 6.411]}
        scale={0.705}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.Rope}
        position={[-6.879, 9.917, 6.345]}
        scale={[0.816, 1, 0.816]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.Silver}
        position={[-6.879, 4.992, 6.273]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.Silver}
        position={[-6.879, 7.552, 3.934]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Wood}
        position={[-6.879, 4.817, 6.273]}
        scale={0.083}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Wood}
        position={[-6.874, 7.38, 4]}
        rotation={[-0.362, 0.023, 0.025]}
        scale={0.083}
      />
      <mesh
        geometry={nodes.WeightRope.geometry}
        material={materials.Rope}
        position={[-6.879, 9.917, 6.345]}
        scale={[0.816, 1, 0.816]}
      />
      <mesh
        geometry={nodes.Weight.geometry}
        material={materials.Silver}
        position={[-6.879, 5.421 + pressureLevel / 5, 3.861]}
      />
      <mesh
        geometry={nodes.BalloonBase.geometry}
        material={materials.StoneFloor}
        position={[-6.876, 4.79, 4.972]}
      />
    </group>
  );
}

useGLTF.preload('./models/Balloon.glb');
