/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Barometer.glb 
*/

import React, { useRef } from 'react';
import { Cylinder, MeshTransmissionMaterial, useGLTF } from '@react-three/drei';
import { MeshBasicMaterial, MeshPhysicalMaterial } from 'three';

export default function Model({ pressure = 965, trigger }, props) {
  const { nodes, materials } = useGLTF('./models/Barometer.glb');

  const pressureLevel = pressure - 960;
  return (
    <group
      {...props}
      dispose={null}
      position={[0, -10.1, 0]}
      onPointerOver={(event) => (event.stopPropagation(), trigger('pressure'))}
      onPointerOut={(event) => trigger('')}
    >
      <group position={[2.842, 8.958, -0.883]} scale={0.19}>
        <mesh geometry={nodes.Sphere002_1.geometry}>
          <MeshTransmissionMaterial
            transmission={0.9}
            thickness={0.01}
            color={'#FFFFFF'}
          />
        </mesh>
        <Cylinder
          args={[0.8, 0.8, pressureLevel + 20, 18, 1, false]}
          position={[0, pressureLevel / 2 - 5, 0]}
        >
          <meshStandardMaterial color='#3D97A0' transparent opacity={0.8} />
        </Cylinder>

        <mesh
          geometry={nodes.Sphere002_2.geometry}
          material={materials.Brass}
        />
      </group>
      <group position={[2.842, 6.093, -0.883]} scale={[0.937, 0.74, 0.937]}>
        <mesh
          geometry={nodes.Sphere003_1.geometry}
          material={materials.Default}
        />
        <mesh
          geometry={nodes.Sphere003_2.geometry}
          material={materials.Brass}
        />
      </group>
      <mesh
        geometry={nodes.BarometerWater.geometry}
        position={[2.842, 6.15, -0.883]}
        scale={0.887}
      >
        <MeshTransmissionMaterial
          transmission={0.8}
          distortion={1}
          thickness={0.01}
          color={'#3D97A0'}
          temporalDistortion={0.2}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/Barometer.glb');
