/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/BaseWWindLighthouse.glb 
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ trigger, lastHourRainAmount = 0, ...props }) {
  const { nodes, materials } = useGLTF('./models/Barrels.glb');

  const [barrelCount, setBarrelCount] = useState(0);

  useEffect(() => {
    setBarrelCount(lastHourRainAmount);
  }, [lastHourRainAmount]);

  return (
    <group {...props} dispose={null} position={[0, -10.1, 0]}>
      <group
        onPointerOver={(event) => (
          event.stopPropagation(), trigger('lastHourRainAmount')
        )}
        onPointerOut={(event) => trigger('')}
      >
        <group position={[-6.776, 6.572, -3.909]} scale={0.275}>
          <mesh
            geometry={nodes.Cylinder002.geometry}
            material={materials.WoodnPlanks}
          />
          <mesh
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.Brass}
          />
          <mesh
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.Dark}
          />
        </group>
        {barrelCount > 0 && (
          <group
            position={[-8.068, 6.456, -6.429]}
            rotation={[0, 1.566, -3.142]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder003.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder003_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
        {barrelCount > 1 && (
          <group
            position={[-8.536, 6.456, -6.826]}
            rotation={[0, 1.195, 0]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder004.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder004_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
        {barrelCount > 2 && (
          <group
            position={[-7.964, 6.456, -7.025]}
            rotation={[0, 0.423, 0]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder005.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder005_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
        {barrelCount > 3 && (
          <group
            position={[-8.191, 7.252, -6.794]}
            rotation={[0, -0.686, 0]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder006.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder006_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
        {barrelCount > 4 && (
          <group
            position={[-7.455, 6.392, -6.633]}
            rotation={[0.026, 1.404, -1.498]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder007.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder007_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
        {barrelCount > 5 && (
          <group
            position={[-6.882, 6.592, -6.901]}
            rotation={[-0.079, 0.416, 0.193]}
            scale={0.275}
          >
            <mesh
              geometry={nodes.Cylinder008.geometry}
              material={materials.WoodnPlanks}
            />
            <mesh
              geometry={nodes.Cylinder008_1.geometry}
              material={materials.Brass}
            />
          </group>
        )}
      </group>
    </group>
  );
}

useGLTF.preload('./models/Barrels.glb');
