/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ThermoHouse.glb 
*/

import React, { useMemo, useRef } from 'react';
import * as THREE from 'three';
import {
  MeshReflectorMaterial,
  MeshTransmissionMaterial,
  useGLTF,
} from '@react-three/drei';

export default function Model(
  { temperature, openDrawer, temperatureRef, trigger },
  props
) {
  const { nodes, materials } = useGLTF('./models/ThermoHouse.glb');
  // const temperature = 30;
  const planes = useMemo(
    () => [
      new THREE.Plane(
        new THREE.Vector3(0, -1, 0),
        0.04125 * temperature - 0.73
      ), // 40
    ],
    [temperature]
  );

  // const planeHelper = useMemo(
  //   () => new THREE.PlaneHelper(planes[0], 15, 0xff0000), // Create a PlaneHelper for visualization
  //   [planes]
  // );
  return (
    <>
      <group
        {...props}
        dispose={null}
        position={[0, -10.1, 0]}
        onPointerOver={(event) => (
          event.stopPropagation(), trigger('temperature')
        )}
        onPointerOut={(event) => trigger('')}
        onClick={(event) => openDrawer(temperatureRef)}
      >
        <mesh
          geometry={nodes.Sphere004.geometry}
          position={[5.868, 8.28, -7.286]}
          scale={0.663}
        >
          <meshStandardMaterial color='#64748b' transparent opacity={0.3} />
        </mesh>
        <mesh
          geometry={nodes.NurbsPath001.geometry}
          material={materials.Glass}
          position={[5.868, 9.422, -7.286]}
          scale={0.663}
        >
          <meshStandardMaterial color='#64748b' transparent opacity={0.3} />
          {/* <MeshTransmissionMaterial
          backside
          backsideThickness={5}
          thickness={0.5}
          resolution={1024}
        /> */}
        </mesh>
        <group position={[5.868, 11.477, -7.286]} scale={[1.362, 0.291, 1.362]}>
          <mesh
            geometry={nodes.Cone001_1.geometry}
            material={materials.Default}
          />
          <mesh
            geometry={nodes.Cone001_2.geometry}
            material={materials.Brass}
          />
          <mesh geometry={nodes.Cone001_3.geometry} material={materials.Wood} />
        </group>
        <mesh
          geometry={nodes.Cone001.geometry}
          material={materials.Brass}
          position={[6.531, 11.741, -7.286]}
        />
        <mesh
          geometry={nodes.Termoliquid.geometry}
          material={materials.ThermoMat}
          position={[5.868, 9.422, -7.286]}
          scale={0.663}
          material-clippingPlanes={planes}
          material-clipShadows={true}
        />
        <mesh
          geometry={nodes.Sphere005.geometry}
          material={materials.ThermoMat}
          position={[5.868, 8.28, -7.286]}
          scale={0.663}
        />
      </group>
      {/* <primitive object={planeHelper} /> */}
    </>
  );
}

useGLTF.preload('./models/ThermoHouse.glb');
